server:
  port: 13000
#eureka配置
eureka:
  instance:
    hostname: eurekaServer13000

  client:
    register-with-eureka: false  #是否将自己注册到eureka 服务当中（默认true）.
    fetch-registry: false #是否启用从注册中心拉取服务列表的功能（默认true）.
    service-url:
      #这是集群版写法，13000注册给13001；反之，13001要注册给13000.
      defaultZone: http://eurekaServer13001:13001/eureka/

  server:
    enable-self-preservation: false
